# Site
name: 'Mainframe to Cloud'
description: 'Mainframe and Cloud Architecture, Engineering'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'mainframe2cloud-com'
email: 'mainframe2cloud@gmail.com'
#mailchimp-list: 'https://mainframe2cloud.us6.list-manage.com/subscribe/post?u=d23d4ad5e48d0a28930337cef&amp;id=92539b7ce9'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

authors:
    ming:
      name:           Ming
      site:           https://www.mainframe2cloud.com
      avatar:         /assets/images/avatar1.jpg
      bio:            "Hi, This is Ming - Head of Infra Engineering. I focus on Mainframe to Cloud, Cybersecurity and Data Analytic."
      email:          mainframe2cloud@gmail.com
      twitter:        https://www.linkedin.com/in/billrain/

    johnny:
      name:           New Authors
      site:           https://www.mainframe2cloud.com
      avatar:         /assets/images/avatar2.jpg
      bio:            "Welsome join us!"
      email:          test@gmail.com
      twitter:        https://www.linkedin.com/in/billrain/

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: ming
      avatar: /assets/images/avatar1.jpg

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
